apiVersion: apps/v1
kind: Deployment
metadata:
  name: componentes-eletronicos-front
spec:
  selector:
    matchLabels:
      app: componentes-eletronicos-front
  template:
    metadata:
      labels:
        app: componentes-eletronicos-front
    spec:
      containers:
      - name: componentes-eletronicos-front
        image: vximoraes/componentes-eletronicos-front:latest
        resources: {}
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: componentes-eletronicos
spec:
  selector:
    app: componentes-eletronicos-front
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
