apiVersion: v1
kind: ConfigMap
metadata:
  name: componentes-eletronicos-front-env
  labels:
    io.kompose.service: componentes-eletronicos-front
data:
  # =============================================================================
  # CONFIGURAÇÕES DO FRONTEND
  # =============================================================================
  PORT: "3000"
  NODE_ENV: "production"
  DEBUGLOG: "false"

  # =============================================================================
  # URLs
  # =============================================================================
  NEXT_PUBLIC_API_URL: "http://localhost:3010"
  API_URL: "http://localhost:3010"